export default [
    {
        "_id": "Q101",
        "title": "JavaScript Basics Quiz",
        "course": "CS101",
        "description": "Test your knowledge of JavaScript fundamentals.",
        "points": 50,
        "quizType": "Graded Quiz",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "maxAttempts": 1,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-05-20",
        "availableFrom": "2024-05-10",
        "availableUntil": "2024-05-25"
    },
    {
        "_id": "Q102",
        "title": "React Components Quiz",
        "course": "CS101",
        "description": "Evaluate your understanding of React components and their lifecycle.",
        "points": 75,
        "quizType": "Graded Quiz",
        "shuffleAnswers": true,
        "timeLimit": 30,
        "multipleAttempts": true,
        "maxAttempts": 3,
        "showCorrectAnswers": true,
        "accessCode": "reactquiz",
        "oneQuestionAtATime": false,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "dueDate": "2024-06-01",
        "availableFrom": "2024-05-20",
        "availableUntil": "2024-06-05"
    },
    {
        "_id": "Q201",
        "title": "Data Structures Quiz",
        "course": "CS201",
        "description": "Quiz on linked lists, stacks, and queues.",
        "points": 100,
        "quizType": "Graded Quiz",
        "shuffleAnswers": true,
        "timeLimit": 40,
        "multipleAttempts": false,
        "maxAttempts": 1,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-06-10",
        "availableFrom": "2024-06-01",
        "availableUntil": "2024-06-15"
    },
    {
        "_id": "Q202",
        "title": "Algorithm Design Quiz",
        "course": "CS201",
        "description": "Test your skills in designing algorithms for optimization problems.",
        "points": 120,
        "quizType": "Graded Quiz",
        "shuffleAnswers": true,
        "timeLimit": 45,
        "multipleAttempts": true,
        "maxAttempts": 2,
        "showCorrectAnswers": true,
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": true,
        "dueDate": "2024-06-20",
        "availableFrom": "2024-06-10",
        "availableUntil": "2024-06-25"
    },
    {
        "_id": "Q301",
        "title": "Machine Learning Basics Quiz",
        "course": "CS301",
        "description": "A quiz on basic concepts of machine learning.",
        "points": 80,
        "quizType": "Practice Quiz",
        "shuffleAnswers": false,
        "timeLimit": 25,
        "multipleAttempts": true,
        "maxAttempts": 5,
        "showCorrectAnswers": true,
        "accessCode": "mlquiz",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-07-01",
        "availableFrom": "2024-06-20",
        "availableUntil": "2024-07-05"
    },
    {
        "_id": "Q302",
        "title": "Deep Learning Quiz",
        "course": "CS301",
        "description": "Evaluate your understanding of neural networks and deep learning concepts.",
        "points": 150,
        "quizType": "Graded Quiz",
        "shuffleAnswers": true,
        "timeLimit": 60,
        "multipleAttempts": false,
        "maxAttempts": 1,
        "showCorrectAnswers": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "dueDate": "2024-07-10",
        "availableFrom": "2024-07-01",
        "availableUntil": "2024-07-15"
    }
];
